version: '3.8'
services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cocktails
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - TOKEN_SIGNING_KEY=413F4428472B4B6250655321321ASD123JH68566D5970337336763979244226452948404D6351

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cocktails
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - cocktails-data:/var/lib/postgresql/data

volumes:
  cocktails-data: