server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cocktails
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none

token:
  signing:
    key: 413F4428472B4B6250655321321ASD123JH68566D5970337336763979244226452948404D6351